plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.code.gson:gson:2.11.0")
    testImplementation(platform("org.junit:junit-bom:5.13.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("com.approvaltests:approvaltests:26.0.0")
    testImplementation("org.mockito:mockito-core:5.12.0")
}

group = 'com.guitarshack'
version = '1.0-SNAPSHOT'
description = 'guitarshack'

application {
    mainClass = 'com.guitarshack.Program'
}

test {
    useJUnitPlatform()
    failOnNoDiscoveredTests = false
    testLogging {
        events "passed", "skipped", "failed"
    }
}
